Repository solidusio/solidus_starter_frontend, pull requests merged in 2020-06, with the labels that each got.

#52 Update orders controller and specs to match Solidus
  app/controllers/spree/orders_controller.rb
  spec/controllers/spree/current_order_tracking_spec.rb
  spec/controllers/spree/orders_controller_spec.rb
Labels: bug

#47 Footer component
  app/views/spree/components/layout/_footer.html.erb
  app/views/spree/layouts/spree_application.html.erb
Labels: refactor

#48 Remove unused partials
  app/views/spree/shared/_address.html.erb
  app/views/spree/shared/_locale_selector.erb
  app/views/spree/shared/_nav_bar.html.erb
Labels: refactor

#53 Refactor JavaScript v2
  .eslintrc
  .hound.yml
  app/assets/javascripts/spree/frontend/product.js
Labels: enhancement

#49 Refactor JavaScript v1
  app/assets/javascripts/spree/frontend/cart.js
  app/assets/stylesheets/spree/frontend/components/cart/_cart_item.scss
  app/views/spree/components/cart/_cart_item.html.erb
Labels: refactor

#54 Remove code that generate deprecation warnings
  app/controllers/spree/checkout_controller.rb
  app/controllers/spree/orders_controller.rb
  spec/controllers/spree/checkout_controller_spec.rb
  spec/controllers/spree/orders_controller_spec.rb
Labels: enhancement, refactor

#60 Refactor JavaScript v4
  app/assets/javascripts/spree/frontend/checkout/payment.js
Labels: enhancement

#56 Refactor JavaScript v3
  app/assets/javascripts/spree/frontend/checkout.js
  app/assets/javascripts/spree/frontend/checkout/coupon-code.js
  app/controllers/spree/coupon_codes_controller.rb
  app/views/spree/components/checkout/_checkout_summary.html.erb
  app/views/spree/components/checkout/_coupon_code.html.erb
  app/views/spree/components/forms/_address_inputs.html.erb
  app/views/spree/components/orders/_coupon_code.html.erb
  spec/system/coupon_code_spec.rb
Labels: enhancement
